version: '3.7'

services:
  db:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    restart: always

volumes:
  mongodb_data: